### PR TITLE
Improve collapsing perf

### PR DESCRIPTION
**Pull request by Sialagio**

### CODE REVIEW

**Comment by zaguiini** [comment]
Sorry, I didn't get it. What's the purpose of this PR?
Do you have evidence on the perf drop?

**Comment by Sialagio** [comment]
Only uncollapsed nodes needs to be rendered.
When a node is collapsed, the treeRender should not be executed.
In the current code, all nodes get rendered.

**Comment by Sialagio** [comment]
Hello,

 

Only uncollapsed nodes needs to be rendered.
When a node is collapsed, the treeRender should not be executed.
In the current code, all nodes get rendered.

**Comment by zaguiini** [comment]
Thanks for the contribution! I decided to rewrite the lib and this bug is now fixed on `v2`.

**Pull request closed without merging**
